### ISSUE TITLE
Combo box dropdown size Linux/Mac

### ISSUE THREAD

**Issue by ljjh20** [royerlab/coPylot#38]
First item in combo box dropdown fills window. Could not fix with changing size policy, setting minimum height, or changing .view().setMaximumHeight. Appears to be a bug with QDarkStyle on Max and Linux: https://github.com/ColinDuquesnoy/QDarkStyleSheet/issues/200

Attempt to fix and check if problem persists on Windows.

**Comment by AhmetCanSolak** [comment]
@ljjh20 you can pass `styleSheet="combobox-popup: 0;"` as keyword argument to your QComboBox() call.  That will do.
